version: '3.1'
services:

  apache:
    build:
      context: .
      # PHP 8.1
      dockerfile: build/apache/php-8.1/Dockerfile
    container_name: drupal_web
    ports:
      - '80:80'
      - '9003:9003'
    volumes:
      - './src:/var/www/html'
      - './var:/var/log'
      - '~/.composer/cache:/var/www/.composer/cache'
    environment:
      XDEBUG_CONFIG: 'remote_host=host.docker.internal remote_port=9003'
      PHP_IDE_CONFIG: serverName=Docker
    depends_on:
      - db
    links:
      - db
    networks:
      - -drupal

  db:
    image: 'mariadb:10.7'
    container_name: drupal_db
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MARIADB_ROOT_PASSWORD=root
      - MYSQL_DATABASE=formation
      - MARIADB_DATABASE=formation
      - MYSQL_USER=admin
      - MARIADB_USER=admin
      - MYSQL_PASSWORD=admin123
      - MARIADB_PASSWORD=admin123
    volumes:
      - './dbdata:/var/lib/mysql'
      - './backups:/var/tmp/backups'
    networks:
      - -drupal

  adminer:
    image: adminer
    container_name: drupal_adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - -drupal

  phpmyadmin:
    image: phpmyadmin
    container_name: drupal_phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=admin
      - PMA_PASSWORD=admin123
    ports:
      - 8081:80
    networks:
      - -drupal


  mailhog:
    image: mailhog/mailhog
    restart: always
    container_name: drupal_mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - -drupal

networks:
  -drupal:
    driver: bridge

volumes:
  dbdata:
    driver: local
